language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - EXTRA=1
  - GEVENT_FILE=thread
matrix:
 allow_failures:
   - env: GEVENT_BACKEND=signalfd
   - python: 2.5
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3
 include:
   - python: 2.7
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3
   - python: 2.7
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3 GEVENT_FILE=thread
   - python: 2.7
     env: GEVENT_BACKEND=select GEVENTSETUP_EV_VERIFY=3
   - python: 2.7
     env: GEVENT_BACKEND=poll GEVENTSETUP_EV_VERIFY=3
   - python: 2.7
     env: GEVENT_BACKEND=nosigmask,noinotify GEVENTSETUP_EV_VERIFY=3
   - python: 2.6
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3
   - python: 2.7
     env: GEVENT_BACKEND=signalfd
   - python: 2.5
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3
install:
 - if [ "`type -t deactivate`" = 'function' ]; then deactivate; fi
 - export VER=$TRAVIS_PYTHON_VERSION$DEBUGPY
 - export PYTHON=/usr/bin/python$VER
 - sudo -E ./travis_install_deps.sh
 - echo $PYTHON && $PYTHON --version
 - sudo $PYTHON setup.py install
script:
 - cd greentest && $PYTHON testrunner.py --full --expected ../known_failures.txt
notifications:
  email:
    recipients:
      - denis.bilenko@gmail.com
    on_success: change
    on_failure: change
